### ISSUE TITLE
Link is niet clickable door position: sticky en z-index css.. 

### ISSUE THREAD

**Issue by KoopReynders** [fdnd/oc.fdnd.nl#5]
https://github.com/fdnd/oc.fdnd.nl/blob/0b5a99f8ccdf3d3ffb76bc034ac0c715c20ba52b/index.html#L95

Dat kan wel met CSS, maar hoe? 
@joostf  jij weet dit ook toch?

**Comment by joostf** [comment]
Yes, in dit geval hoef je de `pointer-events` property niet te gebruiken. Links in de `<header>` zijn nu niet klikbaar omdat de `z-index` op `-1` staat. 

Dit zou moeten werken:

```css
header {
  position:sticky;
  z-index:1;
  ...
}

article {
  position:relative;
  z-index:2;
  pointer-events:auto; /* deze regel kan weg, omdat dat de default is */
  ...
}
```

Als ik goed begrijp wat er moet gebeuren 😁
